#!/usr/bin/env bash
# Script that installs Nginx and configure it
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
systemctl start nginx
chown -R ubuntu:ubuntu/var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
systemctl restart nginx
