#!/usr/bin/env bash
# Script that installs Nginx and configure it
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
systemctl start nginx
chown -R $ubuntu:$ubuntu /var/www
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
systemctl restart nginx
