#!/usr/bin/env bash
# Script that installs Nginx and configure it
apt-get -y update
apt-get -y install nginx
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "26i $redirect" /etc/nginx/sites-available/default
service nginx restart
