#!/usr/bin/env bash
# Script that installs Nginx and configure it
apt-get -y update
apt-get -y install nginx
service nginx start
redirect="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "30i $redirect" /etc/nginx/sites-available/default
service nginx restart
