#!/usr/bin/env bash
# Configures a server with nginx adding a custo header
apt-get -y update
apt-get -y install nginx
service nginx start
line="\\\tadd_header X-Served-By \$hostname;"
sed -i -e "/sendfile on;/a $line" /etc/nginx/nginx.conf
service nginx reload