#!/usr/bin/env bash
# installs and configure HAproxy
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy
echo "listen 1308-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\tserver 1308-web-01 35.237.127.243:80 check\n\tserver 1308-web-02 54.90.102.32:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart