#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
echo $BASHPID > /var/run/holbertonscript.pid
while true
do
  echo "To infinity and beyond"
  trap "echo I hate the kill command" SIGTERM
  trap "echo Y U no love me?!" SIGINT
  trap 'rm /var/run/holbertonscript.pid; kill -9 $BASHID' SIGQUIT
  sleep 2
done
