#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
touch /var/run/holbertonscript.pid
while true
do
  echo "To infinity and beyond"
  trap "echo 'I hate the kill command'; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
  trap "echo 'Y U no love me?!'" SIGINT
  trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
  sleep 2
done
