#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
hol="holbertonschool"
if [ -e "$hol" ]
then
  echo "holbertonschool file exists"
  if [ -s "$hol" ]
  then
    echo "holbertonschool file is not empty"
  else
    echo "holbertonschool file is empty"
  fi
  if ! [ -d "$hol" ]
  then
    echo "holbertonschool is a regular file"
  fi
else
  echo "holbertonschool file does not exist"
fi
